### ISSUE TITLE
where can i get model file and anyother model

### ISSUE THREAD

**Issue by LaviLiu** [hwang1996/Set-to-Set-Recognition#1]

**Comment by LaviLiu** [comment]
where can i get models-7-symbol.json, models-7-0107.params ? Is these all codes？I can not find train_info and train_model. Can you share all code for us?

**Comment by morrychan** [comment]
I think highly of  your work and have great interest in it.Would you please share all the code for further reasearch?

**Comment by skJack** [comment]
which dataset you used in this code?

**Comment by hwang1996** [comment]
Sorry guys, I used the model pre-trained on the internal large-scale face dataset, so I cannot share the full files. I finetuned with CASIA dataset, where images of single person have large variations.
