### ISSUE TITLE
would you please share all the codes for us to resaerch

### ISSUE THREAD

**Issue by morrychan** [hwang1996/Set-to-Set-Recognition#2]

**Comment by hwang1996** [comment]
Sorry that full files cannot be provided, but you may seek collaborations with Horizon Robotics Inc. Beijing, thanks!

**Comment by Maxwell2017** [comment]
hey guy, how can i get models-7-symbol.json and models-7-0107.params ? I can not find train_info and train_model.

**Comment by Maxwell2017** [comment]
hey guy, can i get models-7-symbol.json and models-7-0107.params ? I can not find train_info and train_model. If not, would you like share your approach concisely？thx anyway
